services:
  backend:
    build:
      context: ./server
      dockerfile: ../docker/backend.dev.Dockerfile
    container_name: dm-portfolio-backend-dev
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: development

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dev.Dockerfile
    container_name: dm-portfolio-frontend-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
